In [1]:
from adaptive_snf_functions import *
import snf

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification

# Generate a dummy dataset for testing the boruta_top_n_features function
# Creating a classification dataset with 100 samples, 20 features, and 2 informative features
X, y = make_classification(n_samples=100, n_features=50, n_informative=2, n_classes=2, random_state=42)

# Convert to pandas DataFrame for easier manipulation
X_df1 = pd.DataFrame(X, columns=[f'Feat_mod1_{i+1}' for i in range(X.shape[1])])
y_df1 = pd.DataFrame(y, columns=['Target'])

X, y = make_classification(n_samples=100, n_features=60, n_informative=2, n_classes=2, random_state=42)

# Convert to pandas DataFrame for easier manipulation
X_df2 = pd.DataFrame(X, columns=[f'Feat_mod2_{i+1}' for i in range(X.shape[1])])
y_df2 = pd.DataFrame(y, columns=['Target'])


# Display the first few rows of the dummy dataset
X_df1.head(), y_df1.head()

(   Feat_mod1_1  Feat_mod1_2  Feat_mod1_3  Feat_mod1_4  Feat_mod1_5  \
 0     0.574071     0.913772     1.103877     1.061371    -1.365824   
 1     0.877362    -0.003603    -1.583903     0.447709     0.208383   
 2     0.810808     0.288694    -1.193637     0.287124     1.304340   
 3    -0.846357     0.067856     0.919229    -0.799192    -0.334775   
 4    -0.272545    -0.553090     0.102485     0.876169    -1.356936   
 
    Feat_mod1_6  Feat_mod1_7  Feat_mod1_8  Feat_mod1_9  Feat_mod1_10  ...  \
 0     1.308576     0.257976     1.230001     0.361661      1.399595  ...   
 1     1.627489    -2.423879     0.640843     1.329153     -0.220964  ...   
 2    -1.416933     1.775311    -0.214921     0.361504      0.793489  ...   
 3    -0.561560    -1.438278     1.412221    -0.953329     -0.643550  ...   
 4    -0.963142    -0.844324     0.099887    -0.061076     -0.340599  ...   
 
    Feat_mod1_41  Feat_mod1_42  Feat_mod1_43  Feat_mod1_44  Feat_mod1_45  \
 0     -0.964705     -1.092164  

In [3]:
num_features=10
selected_genes1, feature_ranks1=feature_selection(X_df1,np.ravel(y_df1),num_features=num_features,n_estimators=100)
feature_ranks1

Feature  Rank
0   Feat_mod1_6     1
1  Feat_mod1_26     1
2  Feat_mod1_23     1
3  Feat_mod1_44     2
4  Feat_mod1_40     2
5  Feat_mod1_12     2
6  Feat_mod1_11     2
7  Feat_mod1_37     3
8  Feat_mod1_25     4
9  Feat_mod1_42     4

In [4]:
num_features=18
selected_genes2, feature_ranks2=feature_selection(X_df2,np.ravel(y_df2),num_features=num_features,n_estimators=50)
feature_ranks2

Feature  Rank
0   Feat_mod2_60     1
1   Feat_mod2_57     1
2   Feat_mod2_26     1
3   Feat_mod2_10     2
4    Feat_mod2_6     3
5   Feat_mod2_21     4
6   Feat_mod2_25     5
7   Feat_mod2_19     6
8   Feat_mod2_47     7
9    Feat_mod2_8     8
10  Feat_mod2_11     9
11   Feat_mod2_3    10
12  Feat_mod2_34    11
13  Feat_mod2_24    12
14  Feat_mod2_28    13
15   Feat_mod2_4    13
16  Feat_mod2_40    15
17  Feat_mod2_30    16

In [5]:
X_df1=X_df1[selected_genes1]
X_df2=X_df2[selected_genes2]

In [6]:
sorted_weights = process_feature_weights_and_mad(
    X_v2_list=[X_df1, X_df2],
    feature_ranks_list=[feature_ranks1, feature_ranks2],
    betta=0.5,
)

In [7]:
sorted_weights[0]

Feature       Rank       mad  rank_norm  mad_norm  feature_weight
0   Feat_mod1_6  22.000000  1.014608   1.000000  0.841313        0.959508
1  Feat_mod1_26  22.000000  0.838997   1.000000  0.536888        0.876609
2  Feat_mod1_23  22.000000  1.106148   1.000000  1.000000        1.000000
3  Feat_mod1_44  11.000000  1.079625   0.333333  0.954022        0.802295
4  Feat_mod1_40  11.000000  0.616385   0.333333  0.150987        0.492098
5  Feat_mod1_12  11.000000  0.616312   0.333333  0.150860        0.492033
6  Feat_mod1_11  11.000000  0.529287   0.333333  0.000000        0.408248
7  Feat_mod1_37   7.333333  0.731890   0.111111  0.351216        0.480795
8  Feat_mod1_25   5.500000  0.688049   0.000000  0.275216        0.370956
9  Feat_mod1_42   5.500000  0.679570   0.000000  0.260519        0.360915

In [8]:
sorted_weights[1]

Feature        Rank       mad  rank_norm  mad_norm  feature_weight
0   Feat_mod2_60  137.000000  1.014608   1.000000  0.840873        0.959394
1   Feat_mod2_57  137.000000  0.838997   1.000000  0.535604        0.876243
2   Feat_mod2_26  137.000000  1.106148   1.000000  1.000000        1.000000
3   Feat_mod2_10   68.500000  0.612140   0.466667  0.141252        0.551325
4    Feat_mod2_6   45.666667  0.665078   0.288889  0.233276        0.510962
5   Feat_mod2_21   34.250000  1.079625   0.200000  0.953895        0.759571
6   Feat_mod2_25   27.400000  0.530882   0.146667  0.000000        0.270801
7   Feat_mod2_19   22.833333  0.630425   0.111111  0.173037        0.376927
8   Feat_mod2_47   19.571429  0.657300   0.085714  0.219756        0.390813
9    Feat_mod2_8   17.125000  0.771351   0.066667  0.418013        0.492280
10  Feat_mod2_11   15.222222  0.578566   0.051852  0.082890        0.259559
11   Feat_mod2_3   13.700000  0.573493   0.040000  0.074071        0.238821
12  Feat_mod2_34   12.454545  0.850692   0.030303  0.555933        0.541404
13  Feat_mod2_24   11.416667  0.627096   0.022222  0.167251        0.307793
14  Feat_mod2_28   10.538462  0.618931   0.015385  0.153058        0.290209
15   Feat_mod2_4   10.538462  0.646670   0.015385  0.201277        0.329136
16  Feat_mod2_40    9.133333  0.747650   0.004444  0.376813        0.436611
17  Feat_mod2_30    8.562500  0.658598   0.000000  0.222011        0.333175

In [14]:
similarity_view1_w = make_affinity_with_weight(X_df1,weight=sorted_weights[0]['feature_weight'].to_list())
similarity_view2_w = make_affinity_with_weight(X_df2,weight=sorted_weights[1]['feature_weight'].to_list())

fused_network = SNF_modality_weights([similarity_view1_w, similarity_view2_w], weight_modality=[0.8, 0.2])
print('fused_network', fused_network)

fused_network [[1.17308747 0.00160146 0.00226929 ... 0.00586478 0.00390996 0.00243464]
 [0.00160146 1.16019481 0.00163952 ... 0.00164705 0.00176093 0.00187678]
 [0.00226929 0.00163952 1.1608956  ... 0.00452224 0.00688077 0.00131147]
 ...
 [0.00586478 0.00164705 0.00452224 ... 1.17366293 0.00718276 0.00232364]
 [0.00390996 0.00176093 0.00688077 ... 0.00718276 1.16599084 0.00449123]
 [0.00243464 0.00187678 0.00131147 ... 0.00232364 0.00449123 1.16174763]]


In [15]:
fused_network.shape

(100, 100)

In [16]:
similarity_view1= snf.make_affinity(X_df1)
similarity_view2 = snf.make_affinity(X_df2)

fused_network_simple = snf.snf([similarity_view1, similarity_view2])
print('fused_network', fused_network_simple)

fused_network [[0.56739673 0.01026194 0.00906618 ... 0.00936463 0.00948705 0.00915827]
 [0.01026194 0.56496514 0.00941962 ... 0.00902489 0.00895452 0.00890067]
 [0.00906618 0.00941962 0.56331497 ... 0.0094115  0.01040282 0.00883629]
 ...
 [0.00936463 0.00902489 0.0094115  ... 0.56497488 0.01021846 0.01004981]
 [0.00948705 0.00895452 0.01040282 ... 0.01021846 0.56296449 0.00902569]
 [0.00915827 0.00890067 0.00883629 ... 0.01004981 0.00902569 0.56301315]]


In [17]:
similarity_view1= snf.make_affinity(X_df1)
similarity_view2 = snf.make_affinity(X_df2)

fused_network_mod = SNF_modality_weights([similarity_view1, similarity_view2],weight_modality=[1,1,])
print('fused_network', fused_network_mod)

fused_network [[0.56739673 0.01026194 0.00906618 ... 0.00936463 0.00948705 0.00915827]
 [0.01026194 0.56496514 0.00941962 ... 0.00902489 0.00895452 0.00890067]
 [0.00906618 0.00941962 0.56331497 ... 0.0094115  0.01040282 0.00883629]
 ...
 [0.00936463 0.00902489 0.0094115  ... 0.56497488 0.01021846 0.01004981]
 [0.00948705 0.00895452 0.01040282 ... 0.01021846 0.56296449 0.00902569]
 [0.00915827 0.00890067 0.00883629 ... 0.01004981 0.00902569 0.56301315]]
